# Generated by Django 6.0.3 on 2026-03-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='administrative_level',
            field=models.CharField(choices=[('COUNTRY', 'Kenya'), ('ADMIN_1', 'County'), ('ADMIN_2', 'Sub-County'), ('ADMIN_3', 'Ward')], db_index=True, default='ADMIN_1', max_length=50, verbose_name='Administrative Level'),
        ),
    ]
