"""
Django settings for kilimostat4 project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
import environ
import logging
from pathlib import Path
from datetime import timedelta
from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured

# ============================================================================
# ENVIRONMENT CONFIGURATION
# ============================================================================

# Initialize environment variables
env = environ.Env(
    # Set casting and default values
    DEBUG=(bool, False),
    SECRET_KEY=(str, 'django-insecure-default-key-change-in-production'),
    ALLOWED_HOSTS=(list, []),
    CORS_ALLOWED_ORIGINS=(list, []),
    DATABASE_URL=(str, 'sqlite:///db.sqlite3'),
    REDIS_URL=(str, 'redis://localhost:6379'),
    EMAIL_URL=(str, 'console://'),
    SENTRY_DSN=(str, ''),
    ENVIRONMENT=(str, 'development'),
    
    # Database settings
    DB_NAME=(str, 'kilimostat4'),
    DB_USER=(str, 'postgres'),
    DB_PASSWORD=(str, 'postgres'),
    DB_HOST=(str, 'localhost'),
    DB_PORT=(str, '5432'),
    
    # Email settings
    EMAIL_HOST=(str, 'smtp.gmail.com'),
    EMAIL_PORT=(int, 587),
    EMAIL_HOST_USER=(str, ''),
    EMAIL_HOST_PASSWORD=(str, ''),
    EMAIL_USE_TLS=(bool, True),
    
    # API settings
    API_BASE_URL=(str, 'http://localhost:8000/api'),
    API_RATE_LIMIT=(int, 100),
    
    # Cache settings
    CACHE_TTL=(int, 300),
    
    # File upload
    MAX_UPLOAD_SIZE=(int, 10485760),  # 10MB
    ALLOWED_UPLOAD_EXTENSIONS=(list, ['.csv', '.xlsx', '.xls', '.json']),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
env_file = os.path.join(BASE_DIR, '.env')
if os.path.exists(env_file):
    environ.Env.read_env(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# FIXED: ALLOWED_HOSTS should be properly parsed from env
# The env('ALLOWED_HOSTS') returns a list, but we need to ensure it's properly formatted
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# ============================================================================
# APPLICATION DEFINITION
# ============================================================================

INSTALLED_APPS = [
    # Django Admin Theme (must come first)
    'admin_interface',
    'colorfield',
    
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    'drf_yasg',
    'import_export',
    'debug_toolbar',
    'django_extensions',
    'drf_spectacular',
    
    # Celery
    'django_celery_beat',
    'django_celery_results',
    
    # Storage and forms
    'storages',
    'widget_tweaks',
    'crispy_forms',
    'crispy_bootstrap5',
    'djcelery_email',
    'axes',
    'mptt',
    'simple_history',
    'guardian',
    
    # Local apps
    'core',
    'dashboard',
    'api',
    'data_import',
]

# Only add tagulous if installed
try:
    import tagulous
    INSTALLED_APPS.append('tagulous')
except ImportError:
    pass

MIDDLEWARE = [
    # Security and performance
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    # Debug
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    
    # Django core
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Third-party
    'axes.middleware.AxesMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'kilimostat4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kilimostat4.wsgi.application'

# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================

# Check if we're running tests
TESTING = sys.argv[1:2] == ['test']

# PostgreSQL for production
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'ATOMIC_REQUESTS': True,
        'CONN_MAX_AGE': 600,
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}

# Database connection pooling (for production)
if not DEBUG and not TESTING and 'postgresql' in DATABASES['default']['ENGINE']:
    DATABASES['default']['POOL_OPTIONS'] = {
        'POOL_SIZE': 20,
        'MAX_OVERFLOW': 10,
        'RECYCLE': 3600,
    }

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# AUTHENTICATION & AUTHORIZATION
# ============================================================================

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Add Axes if installed
try:
    import axes
    AUTHENTICATION_BACKENDS.insert(0, 'axes.backends.AxesStandaloneBackend')
except ImportError:
    pass

# Add Guardian if installed
try:
    import guardian
    AUTHENTICATION_BACKENDS.append('guardian.backends.ObjectPermissionBackend')
except ImportError:
    pass

# Login/Logout URLs
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/'

# Session settings
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF settings
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
# FIXED: Properly handle CSRF_TRUSTED_ORIGINS
CSRF_TRUSTED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY' if not DEBUG else 'SAMEORIGIN'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG

# Axes settings (if installed)
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=30)
AXES_RESET_ON_SUCCESS = True
AXES_ENABLE_ADMIN = True

# Guardian settings (if installed)
if 'guardian' in INSTALLED_APPS:
    ANONYMOUS_USER_NAME = 'anonymous'
    GUARDIAN_RAISE_403 = True

# ============================================================================
# INTERNATIONALIZATION
# ============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True

# Available languages
LANGUAGES = [
    ('en', 'English'),
    ('sw', 'Swahili'),
]

# Locale paths
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# ============================================================================
# STATIC & MEDIA FILES
# ============================================================================

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
#STATIC_ROOT = BASE_DIR / 'staticfiles'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files storage
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = env('MAX_UPLOAD_SIZE')
DATA_UPLOAD_MAX_MEMORY_SIZE = env('MAX_UPLOAD_SIZE')
FILE_UPLOAD_PERMISSIONS = 0o644

# ============================================================================
# EMAIL CONFIGURATION
# ============================================================================

if DEBUG:
    # Console backend for development
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'KilimoSTAT <noreply@kilimostat.com>'
else:
    # SMTP for production
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = env('EMAIL_HOST')
    EMAIL_PORT = env('EMAIL_PORT')
    EMAIL_HOST_USER = env('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
    EMAIL_USE_TLS = env('EMAIL_USE_TLS')
    DEFAULT_FROM_EMAIL = 'KilimoSTAT <datahub@kalro.org>'
    SERVER_EMAIL = 'admin@kilimostat.com'

# ============================================================================
# CACHE CONFIGURATION
# ============================================================================

# Check if Redis is available
try:
    import redis
    REDIS_AVAILABLE = True
except ImportError:
    REDIS_AVAILABLE = False

if DEBUG or not REDIS_AVAILABLE:
    # Use local memory cache for development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'KEY_PREFIX': 'kilimostat',
            'TIMEOUT': env('CACHE_TTL'),
        }
    }
else:
    # Use Redis for production
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': env('REDIS_URL'),
            'KEY_PREFIX': 'kilimostat',
            'TIMEOUT': env('CACHE_TTL'),
        }
    }

# Cache time to live (in seconds)
CACHE_MIDDLEWARE_SECONDS = env('CACHE_TTL')
CACHE_MIDDLEWARE_KEY_PREFIX = 'kilimostat'

# ============================================================================
# CELERY CONFIGURATION
# ============================================================================

if REDIS_AVAILABLE and not DEBUG:
    # Celery settings
    CELERY_BROKER_URL = env('REDIS_URL')
    CELERY_RESULT_BACKEND = 'django-db'
    CELERY_ACCEPT_CONTENT = ['application/json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_TIMEZONE = TIME_ZONE
    CELERY_TASK_TRACK_STARTED = True
    CELERY_TASK_TIME_LIMIT = 30 * 60
    CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

    # Celery beat schedule
    CELERY_BEAT_SCHEDULE = {
        'cleanup-old-data': {
            'task': 'core.tasks.cleanup_old_data',
            'schedule': timedelta(days=30),
        },
        'update-dashboard-cache': {
            'task': 'dashboard.tasks.update_cache',
            'schedule': timedelta(hours=1),
        },
    }

# ============================================================================
# CUSTOM JSON FORMATTER FOR LOGGING
# ============================================================================

class JsonFormatter(logging.Formatter):
    """
    Custom JSON formatter for logging
    """
    def format(self, record):
        import json
        from datetime import datetime
        
        log_record = {
            'time': datetime.fromtimestamp(record.created).isoformat(),
            'level': record.levelname,
            'module': record.module,
            'message': record.getMessage(),
        }
        
        if hasattr(record, 'request_id'):
            log_record['request_id'] = record.request_id
            
        if record.exc_info:
            log_record['exception'] = self.formatException(record.exc_info)
            
        return json.dumps(log_record)

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================

# Create logs directory if it doesn't exist
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
# ============================================================================
# REST FRAMEWORK CONFIGURATION
# ============================================================================

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    'COERCE_DECIMAL_TO_STRING': False,
}

# Add browsable API in debug mode
if DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'].append('rest_framework.renderers.BrowsableAPIRenderer')

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'KilimoSTAT API',
    'DESCRIPTION': 'API for KilimoSTAT Data from the Ministry of Agriculture and Livestock Development in Kenya',
    'VERSION': '4.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'TAGS': [
        {'name': 'areas', 'description': 'Geographic areas with tree structure'},
        {'name': 'providers', 'description': 'Data providers and organizations'},
        {'name': 'sources', 'description': 'Data sources'},
        {'name': 'sectors', 'description': 'Sectors'},
        {'name': 'subsectors', 'description': 'Subsectors'},
        {'name': 'indicators', 'description': 'Indicators'},
        {'name': 'items', 'description': 'Food items'},
        {'name': 'domains', 'description': 'Data domains'},
        {'name': 'units', 'description': 'Units of measurement'},
        {'name': 'subgroups', 'description': 'Subgroups and dimensions'},
        {'name': 'data', 'description': 'KilimoSTAT data records'},
        {'name': 'metadata', 'description': 'Metadata management'},
        {'name': 'statistics', 'description': 'System statistics'},
    ],
}
# ============================================================================
# CORS CONFIGURATION
# ============================================================================

# FIXED: Use env.list for CORS_ALLOWED_ORIGINS
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",  
    "http://127.0.0.1:3001",
    "http://statistics.kilimo.go.ke",
    "https://statistics.kilimo.go.ke",
])

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ============================================================================
# SWAGGER/API DOCS CONFIGURATION
# ============================================================================

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Basic': {
            'type': 'basic'
        },
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        },
    },
    'USE_SESSION_AUTH': True,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch'
    ],
}

# ============================================================================
# THIRD-PARTY APP SETTINGS
# ============================================================================

# Django Admin Interface
X_FRAME_OPTIONS = 'SAMEORIGIN'
SILENCED_SYSTEM_CHECKS = ['security.W019']

# Import Export
IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_CHUNK_SIZE = 1000

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Django Debug Toolbar
if DEBUG:
    INTERNAL_IPS = [
        '127.0.0.1',
        'localhost',
    ]
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
    }

# ============================================================================
# CUSTOM SETTINGS
# ============================================================================

# Site settings
SITE_NAME = 'Kilimostat'
SITE_DOMAIN = 'kilimostat.com'
SITE_EMAIL = 'info@kilimostat.com'

# Data import settings
DATA_IMPORT_SETTINGS = {
    'ALLOWED_EXTENSIONS': env('ALLOWED_UPLOAD_EXTENSIONS'),
    'MAX_FILE_SIZE': env('MAX_UPLOAD_SIZE'),
    'REQUIRED_HEADERS': [
        'AreaName', 'Level', 'TimePeriod', 'Source',
        'Sector', 'Indicator', 'DataValue'
    ],
}

# Dashboard settings
DASHBOARD_SETTINGS = {
    'CACHE_TIMEOUT': 300,
    'MAX_DATA_POINTS': 10000,
}

# API settings
API_SETTINGS = {
    'VERSION': '1.0.0',
    'BASE_URL': env('API_BASE_URL'),
    'ALLOWED_FORMATS': ['json', 'csv', 'excel'],
}

# ============================================================================
# MESSAGE TAGS
# ============================================================================

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# ============================================================================
# SITE ID
# ============================================================================

SITE_ID = 1

# ============================================================================
# ENVIRONMENT-SPECIFIC SETTINGS
# ============================================================================

# Development settings
if DEBUG:
    # Disable some security in development
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    
    # Allow all hosts in development
    ALLOWED_HOSTS = ['*']
    
    # Disable password validators in development
    AUTH_PASSWORD_VALIDATORS = []

# Production settings
if not DEBUG:
    # Security
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Ensure required settings are present
    if SECRET_KEY == 'django-insecure-default-key-change-in-production':
        raise ImproperlyConfigured("SECRET_KEY must be changed in production")
    
    if not ALLOWED_HOSTS or ALLOWED_HOSTS == ['*']:
        raise ImproperlyConfigured("ALLOWED_HOSTS must be set properly in production")

# ============================================================================
# FINAL VALIDATION
# ============================================================================

# Print startup message
if DEBUG:
    print(f"✅ Kilimostat starting in DEVELOPMENT mode")
else:
    print(f"✅ Kilimostat starting in PRODUCTION mode")
    print(f"🌐 Allowed hosts: {ALLOWED_HOSTS}")
